name: Workflow Obtener precio de los combustibles

on:
  schedule:
    - cron: '0 5 * * *' # Todos los días a las 7 de la mañana (CEST)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout a los datos del repositorio
      uses: actions/checkout@v3
      
    - name: Configuración GPG para firmar Commits
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.CLAVE_PRIVADA }}
        passphrase: ${{ secrets.PASS }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    
    - name: Instalación dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar Script de Scraping 
      run: python obtenerPrecioCombustible.py
    
    - name: Commit Cambios
      env:
        EMAIL: ${{ secrets.EMAIL }}
        NAME: ${{ secrets.NOMBRE }}
        FIRMA: ${{ secrets.FIRMA }}
      run: |
        git config --local user.email "$EMAIL"
        git config --local user.name "$NOMBRE"
        git config --local user.signingkey "$FIRMA"
        git add .
        git commit -S -m "Actualización de precios para el día: $(date '+%d-%m-%Y')"
    
    - name: Push Cambios
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
    
